version: '2'
services:
  WebServer:
    image: 'dockersecplayground/linode_lamp:latest'
    stdin_open: true
    tty: true
    ports:
      - '9000:80'
    volumes:
      - './website:/var/www/example.com/public_html/topolinux_agency'
    cap_add:
      - NET_ADMIN
  EntryPoint:
    image: 'dockersecplayground/kali:latest'
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
networks: {}
