version: '2'
services:
  EntryPoint:
    image: 'dockersecplayground/kali:v1.0'
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
  WebServer:
    image: 'dockersecplayground/linode_lamp:v1.0'
    stdin_open: true
    tty: true
    ports:
      - '9000:80'
    volumes:
      - './website:/var/www/example.com/public_html/topolinux_agency'
    cap_add:
      - NET_ADMIN
networks: {}
